project_id = "lkzcbaxecjmdteqvkxox"

[functions.extract-lab-results]
verify_jwt = false

[functions.convert-anamnese]
verify_jwt = false

[functions.analyze-lab-results]
verify_jwt = false

[functions.parse-imaging-report]
verify_jwt = false

[functions.parse-inbody-ocr]
verify_jwt = false

[functions.patient-chat]
verify_jwt = false

[functions.parse-patient-anamnese]
verify_jwt = false